### ISSUE TITLE
Treat "aria" dict like "data" dict

### ISSUE THREAD

**Issue by ryanprior** [fazibear/opal-virtual-dom#10]
Items in the "data" dict are prefixed with `data-` and added to the element's properties. The same needs to be done for the "aria" dict. For example,
```
div data: {toggle: 'dropdown'}, aria: {haspopup: 'true'}
```
should be rendered as
```
<div data-toggle="dropdown" aria-haspopup="true"></div>
```

**Comment by ryanprior** [comment]
Similar discussion of this in React: https://github.com/facebook/react/issues/1259

From that discussion, it may be preferable to support ARIA props like `div aria_haspopup: 'true'` instead of making it a dict. Since we kinda get to create our own API, which do you think is nicer / more idiomatic Ruby?

**Comment by fazibear** [comment]
It's far beyond simple virtual-dom lib. It can be archived by creating simple helpers that will extend virtual-dom functionality. If someone need it just require another gem. 

Feel free to write such an extension. 

I'm a big fan of small specific libraries.

**Comment by fazibear** [comment]
But look at this: https://inesita.fazibear.me/#dom-dsl

This is an `virtual-dom` javascript library feature. Should work ootb.
