### ISSUE TITLE
Content as string param doesn't work on class or id methods

### ISSUE THREAD

**Issue by i-void** [fazibear/opal-virtual-dom#2]
I'm using opal-virtual-dom with inesita, when I wrote this on component;
`h1 'This is header'` it works
but when I wrote this;
`h1.page_heading 'This is header'` it doesn't work

expected result is `<h1 class="page_heading">This is header</h1>`
issue is occurs in `h1.heading! 'This is header'` also

**Comment by fazibear** [comment]
Thanks! For sure it is a bug, will look at this.
