### ISSUE TITLE
Keys in "style" dict could replace underscore with dash

### ISSUE THREAD

**Issue by ryanprior** [fazibear/opal-virtual-dom#9]
CSS properties like `font-family` and `max-width` use many dashes and no underscores. It would be helpful to replace underscores in dictionary key symbols with dashes in the produced style output.

For example, instead of writing:
```
def render
  p style: {color: 'red', 'font-family': 'serif'} do
    text 'red serif text'
  end
end
```
we could instead write:
```
def render
  p style: {color: 'red', font_family: 'serif'} do
    text 'red serif text'
  end
end
```

See also #3, #6

**Comment by fazibear** [comment]
This feature will require to scan every key in the hash every time the dom tree is rendered. It's a big overhead. It's not a problem to create you own helper function to archive this.

Changes made in #6 referes to method names where dash can't be used. Anyway there is one character difference. It's not worth it.
